import type { HarnessRequest, HarnessResponse, ModelResult, RegisteredModel, RouteDecision } from "./types.js";
import { ModelRegistry } from "./registry.js"; import { ProviderRegistry } from "./provider.js"; import type { DecisionEngine } from "./decision.js"; import type { PolicyEngine } from "./policy.js"; import { estimateCost, type TelemetrySink } from "./telemetry.js";
export class Harness {
  constructor(private readonly registry: ModelRegistry, private readonly providers: ProviderRegistry, private readonly decisions: DecisionEngine, private readonly policy: PolicyEngine, private readonly telemetry?: TelemetrySink, private readonly retryCount = 1) {}
  async execute(request: HarnessRequest): Promise<HarnessResponse> {
    const started = Date.now(); const policyDecision = this.policy.evaluate(request); if (!policyDecision.allowed) throw new Error(policyDecision.reason ?? "Request denied by policy");
    const routeStarted = Date.now(); const route = await this.decisions.decide(request, this.registry.getModels()); const routingMs = Date.now() - routeStarted; const candidates = [route.modelId, ...(route.fallbackModels ?? [])]; let retries = 0; let lastError: unknown;
    for (let i = 0; i < candidates.length; i++) { const model = this.registry.getModel(candidates[i]); const provider = this.providers.get(model.provider); for (let attempt = 0; attempt <= this.retryCount; attempt++) { const modelStarted = Date.now(); try { const result = await this.withTimeout(provider.generate(request, model.providerModel), request.requirements?.maxLatencyMs); const latencyMs = Date.now() - started; this.telemetry?.record({ traceId: request.id, task: request.task, route: { selectedModel: model.id, decisionEngine: route.decisionEngine, reason: route.reason }, usage: result.usage, performance: { routingMs, modelMs: Date.now() - modelStarted, totalMs: latencyMs }, cost: { estimatedUsd: estimateCost(result.usage, model.capabilities.costPerMillionInputTokens, model.capabilities.costPerMillionOutputTokens) }, result: { success: true, retries, fallback: i > 0 } }); return { id: request.id, output: result.output, model: model.id, provider: provider.name, usage: result.usage, cost: { estimatedUsd: estimateCost(result.usage, model.capabilities.costPerMillionInputTokens, model.capabilities.costPerMillionOutputTokens) }, latencyMs, route: { ...route, modelId: model.id } }; } catch (error) { lastError = error; retries++; } } }
    this.telemetry?.record({ traceId: request.id, task: request.task, route: { selectedModel: route.modelId, decisionEngine: route.decisionEngine, reason: route.reason }, performance: { routingMs, modelMs: 0, totalMs: Date.now() - started }, result: { success: false, retries, error: String(lastError) } }); throw lastError instanceof Error ? lastError : new Error(String(lastError));
  }
  private async withTimeout<T>(promise: Promise<T>, timeoutMs?: number): Promise<T> { if (!timeoutMs) return promise; return Promise.race([promise, new Promise<T>((_, reject) => setTimeout(() => reject(new Error("Model request timed out")), timeoutMs))]); }
}
